### ISSUE TITLE
Macbook Air M1 support ?

### ISSUE THREAD

**Issue by khurshid-alam** [tripplet/skypeweb4adium#16]
Need arm vesion for this build.  Thanks.

**Comment by tripplet** [comment]
Unfortunately, Adium is dead at this point, as there has been no development in the last 2 years: https://github.com/adium/adium
(Including no Arm support).
So it makes no sense to compile the extension for Arm if Adium itself is x64.

But the x64 version of Adium should still work and load the extension using x64 emulation while Adium is still running.
Which I wouldn't bet on given the current state of development.

I haven't used Adium for a very long time, as it became more and more difficult to fix compilation problems in Adium itself to compile the extension.

**Comment by khurshid-alam** [comment]
@tripplet 

Macos has rosetta where you can run x64 build in arm64. 

Also there are other clients which supports arm. So I am expexting at least a single build of this library even it is bit old and not the latest release or gets fewer releases.

**Comment by tripplet** [comment]
The problem is not arm or rosetta.
The extensions can use rosetta same as Adium and can start.
 
The problem is that Adium no longer compiles with a current Xcode version.
If you make the fixes to the Adium source code to get it to compile again with a current Xcode version I'm happy to compile the extension.
Without compiling Adium it is not possible to compile the extension.
